version: '3.6'
services:
  db:
    image: postgres:14.3-alpine
    build:
      context: ./docker_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - '5432:5432'