<<<<<<< HEAD
version: '3.9'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./app
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
  db:
    container_name: db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_DB: compose-postgres
=======
version: '3.6'
services:
  db:
    image: postgres:14.3-alpine
    build:
      context: ./docker_db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - '5432:5432'
>>>>>>> b8b5a7f87863e5f738b7b0443334c09fcf3dd91d
